version: '3.3'

volumes:

  db_data:
  static_data:


services:

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - GUNICORN_VERSION=${GUNICORN_VERSION}
    env_file: ../backend/.env
    volumes:
      - static_data:/app/backend_static/
      - db_data:/app/db/
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic -c --noinput
        cp -r /app/staticfiles/. /app/backend_static/
        django-admin compilemessages
        gunicorn --bind 0.0.0.0:8000 config.wsgi
    restart: unless-stopped

  gateway:
    image: ${GATEWAY_VERSION}
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/usr/share/nginx/html/static_backend/
    restart: unless-stopped
