# Generated by Django 4.2.2 on 2023-08-21 16:12

import catalog.songs.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required. %(max_chars)s characters or fewer.', max_length=150, unique=True, verbose_name='Name')),
                ('year', catalog.songs.fields.ValidatePositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value can not be less than %(min_value)s.'), django.core.validators.MaxValueValidator(limit_value=32767, message='Value can not be more than %(max_value)s.')], verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'default_related_name': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required. %(max_chars)s characters or fewer.', max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required. %(max_chars)s characters or fewer.', max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', catalog.songs.fields.ValidatePositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value can not be less than %(min_value)s.'), django.core.validators.MaxValueValidator(limit_value=32767, message='Value can not be more than %(max_value)s.')], verbose_name='Position')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.album', verbose_name='Album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song', verbose_name='Song')),
            ],
            options={
                'verbose_name': 'Song in album',
                'verbose_name_plural': 'Songs in albums',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.singer', verbose_name='Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='songs.AlbumSong', to='songs.song'),
        ),
    ]
